### ISSUE TITLE
Erreur dans l'app officielle de Yunohost

### ISSUE THREAD

**Issue by maniackcrudelis** [opi/dokuwiki_ynh#12]
L'app dokuwiki officielle de Yunohost est indiqué comme étant celle-ci.
https://yunohost.org/#/apps_fr

Hors à l'installation c'est le dépôt de beudbeud qui est utilisé (du moins je suppose).
https://github.com/abeudin/dokuwiki_ynh

Mais ce dépôt ne fonctionne pas, il manque SCRIPT_FILENAME et la page de d'administration est inaccessible.

**Comment by opi** [comment]
L'app officielle est bien celle-ci : https://yunohost.org/official.json

Tu peux essayer de rafraichir la liste des apps avant de l'installer (un bouton "rafraichir" dans l'administration web, ou `% yunohost app fetchlist` en cli.

**Comment by maniackcrudelis** [comment]
Effectivement, après mise à jour de la liste des apps, c'est la bonne version qui est installée.
Merci.

**Comment by opi** [comment]
bizarre par contre, la liste des apps doit se mettre a jour toute seule normalement. cc @Kloadut

**Comment by maniackcrudelis** [comment]
C'est une machine virtuelle, dont l'état varie souvent. Ça explique peut-être que la mise à jour n'est pas été faite.
